### PR TITLE
Building stream name when reading and writing to journal

### PR DESCRIPTION
**Pull request by tjaskula**
Building stream name when reading and writing to journal. Fix first implementation

### CODE REVIEW

**Comment by tjaskula** [comment]
@VaughnVernon update for later

**Review by VaughnVernon — APPROVED** [review]
@tjaskula 👍 Are your changes to `Journal` code that is in Java but was missing in C#, or do these changes now put C# ahead of Java?

**Comment by tjaskula** [comment]
@VaughnVernon C# will be ahead. This is necessary to have more fine grained stream naming. Without that for example `Proposal` aggregate root and `ProposalProcess` where writing and reading from the same stream (thirst one events, next one commands) if you use the same `proposalId` as identifier for both

**Comment by VaughnVernon** [comment]
@tjaskula Ok, yes I know that is a problem with the process examples. Do you have a few minutes to add the same for Java? Also I was asking about the Journal. It looks like you added behavior there.

**Comment by tjaskula** [comment]
@VaughnVernon I can add this to the java version as well. I've added overrides to `Journal` so if you pass the class type if will use it's name to append to stream name.

**Comment by VaughnVernon** [comment]
@tjaskula Good. Thanks!

**Comment by tjaskula** [comment]
Could it be merged @VaughnVernon ? (Meaning i have no rights in a case you wonder)

**Pull request merged**
